apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: todolist-service
      port: 8080
      type: REST
      networkVisibility: Public
      context: /todolist
      schemaFilePath: buildspec.yaml